/*
 * This source file was generated by the Gradle 'init' task
 */
packpackagepackpackageageage org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] argsargs
        System.out.packpackageagep().getGreeting());
    }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

  }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

   }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

  }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}


}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

   }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

  }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}



}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

   }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

  }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}




}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

   }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

  }
}

}


}

}

}
}

}


}

}

 }
}

}


}

}

}
}

}


}

}

packpackageagepackpackagegetGreetinpackpackageagepackpackagegetGreetin